### ISSUE TITLE
could not able connect with android

### ISSUE THREAD

**Issue by NeerajThapliyal** [xlui/WebSocketExample#2]
Hi Thanks for provide great example but i am getting  these error in android client logs:
W/xlui.example.i: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (light greylist, reflection)
W/xlui.example.i: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (light greylist, reflection)
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
W/xlui.example.i: Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
    Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
D/StompClient: Connect
D/AbstractConnectionProvider: Emit lifecycle event: ERROR
D/StompClient: Socket closed with error
D/AbstractConnectionProvider: Emit lifecycle event: CLOSED
D/StompClient: Socket closed
D/StompClient: Stomp disconnected
I/xlui: Subscribe to the broadcast
I/Adreno: QUALCOMM build                   : cf57c9c, I1cb5c4d1cc
    Build Date                       : 09/23/18
    OpenGL ES Shader Compiler Version: EV031.25.03.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
    Build Config                     : S L 6.0.7 AArch64
I/Adreno: PFP: 0x005ff112, ME: 0x005ff066
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
I/Toast: Show toast from OpPackageName:app.xlui.example.im, PackageName:app.xlui.example.im
I/xlui.example.i: ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000

please help me on this

**Comment by xlui** [comment]
Hello, If you use AVD provided by Android Studio, you should use this [local address](https://github.com/xlui/WebSocketExample/blob/abcc22b9d1169776e9a57b9c4f4fe782282aa4b3/AndroidClient/app/src/main/java/app/xlui/example/im/conf/Const.java#L12) instead of [genymotion's local address](https://github.com/xlui/WebSocketExample/blob/abcc22b9d1169776e9a57b9c4f4fe782282aa4b3/AndroidClient/app/src/main/java/app/xlui/example/im/conf/Const.java#L13)

**Comment by NeerajThapliyal** [comment]
@xlui i am using android device for testing and i have changed url like this
public static final String address = "ws://192.168.225.168:8080/im/websocket";

**Comment by xlui** [comment]
It seems that Android 8 or higher has disabled cleartext support by default. see [https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted).

I have updated the code with Option 2 metioned by [https://stackoverflow.com/a/50834600](https://stackoverflow.com/a/50834600), and tested on my Android 9. Please pull the latest code and try again 😄

**Comment by NeerajThapliyal** [comment]
@xlui  thanks for solution let me try this

**Comment by NeerajThapliyal** [comment]
@xlui  it's works thanks
